print("Built-In Data Types")
print("Text Type: str")
print("Numeric Types: int, float, complex")
print("Sequence Types: list, tuple, range")
print("Mapping Type: dict")
print("Set Types: set, frozenset")
print("Boolean Type: bool")
print("Binary Types: byte, bytearray, memoryview")
